### ISSUE TITLE
스킨 라이선스 관련..

### ISSUE THREAD

**Issue by ghost** [openNAMU/openNAMU-Skin-Before_Namu#3]
스킨 라이선스를 어떻게 표기 하여야 하는지 답변 부탁드립니다. 나무위키 전직 운영진이신 PPPP님이 만드신 스킨이니 스킨 수정 후 openNAMU-Skin-Before_Namu 스킨의 라이선스를 그대로 따라가면 되는건가요?

**Comment by surplus-dev** [comment]
잉? 답변 달았던 것 같은데 답변이 없네요 깜박했었나

예전에 물어봤을 때는 알아서 하라던데 애매하긴 한데 그냥 원작자 표시 해놓으면 되지 않을까 싶습니다
